### ISSUE TITLE
First Release Checklist - v0.1

### ISSUE THREAD

**Issue by yadvr** [apache/cloudstack-csbench#1]
Some suggestions actions we can consider:

- [x] Explore Github Actions for CI/Lint and Build
- [ ] Maybe use cobra & viper for config management and cli options
- [ ] Merge -benchmark and -create output
- [ ] Add concurrency to benchmark
- [ ] Add more network types
- [ ] Setup logging level at differnt logs and set level according to verbosity setting
- [ ] Review configuration and use
- [ ] Document usage guide in csbench's wiki (Github)

**Comment by yadvr** [comment]
cc @harikrishna-patnala @vishesh92 @kishankavala @vladimirpetrov
